# Generated by Django 3.2 on 2022-11-23 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='teams',
            field=models.ManyToManyField(blank=True, to='assets.Team'),
        ),
    ]
