# Generated by Django 3.2 on 2022-11-24 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_alter_competition_teams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='logo',
            field=models.ImageField(default=2, upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='team',
            name='logo',
            field=models.ImageField(default='hello.jpg', upload_to='images/'),
            preserve_default=False,
        ),
    ]
