# Generated by Django 3.2 on 2022-12-03 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_alter_venue_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='matchId',
            field=models.CharField(max_length=20),
        ),
    ]
