# Generated by Django 3.2 on 2023-01-04 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0007_alter_team_short_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='starting_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
