# Generated by Django 3.2 on 2023-02-20 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0009_auto_20230126_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='addedAt',
            field=models.PositiveBigIntegerField(default=1676920189680475000),
        ),
    ]
